[package]
name = "supraDAFinal"
version = "1.0.0"
authors = []

[addresses]
CAFE = "0xca1538351b280983182d045df013a4b3895331dbe1eab683a175c0faf92ff904"
aptos_token = "0x3"

[dev-addresses]


[dependencies.AptosTokenObjects]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]